name: build 
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  update-readme-and-reset-commits:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install -r requirements.txt
      - run: python3 material/script/readme_writer_main.py

      - name: Reset commits
        run: |
          git checkout --orphan temp
          git add --all
          git config user.name "Akash Singh"
          git config user.email $EMAIL
          git commit -m 'LeetCode Solution'
          git branch -D master
          git branch -m master
          git push origin master -f
        env:
          EMAIL: ${{ secrets.EMAIL }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: update-readme-and-reset-commits
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install -r requirements.txt
      - run: python3 material/script/mkdocs_writer_main.py
        env:
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_X509_CERT_URL: ${{ secrets.CLIENT_X509_CERT_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
          PROJECT_ID: ${{ secrets.PROJECT_ID }}

      - run: cp README.md docs/preface.md

      - name: Mkdocs builds docs to site
        run: |
          mkdocs build -f mkdocs.yml
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site
          publish_branch: gh-pages
          force_orphan: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
